import turtle
t=turtle.Turtle()
w=turtle.Screen()
w.title('PENTAGON')
w.bgcolor('red')
t.up()
t.goto(0,-100)
t.down()
t.pensize(2)
t.begin_fill()
t.fillcolor('dark green')
t.circle(200,None,5)
t.end_fill()
w.exitonclick()