import turtle
t=turtle.Turtle()
w=turtle.Screen()
w.title('TRIANGLE')
w.bgcolor('black')
t.up()
t.goto(0,-100)
t.down()
t.pencolor('white')
t.pensize(2)
t.begin_fill()
t.fillcolor('yellow')
t.circle(200,None,3)
t.end_fill()
w.exitonclick()